package javainventario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import static JavaInventario.Login.My_User_Connected;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Clientes() {
        initComponents();
        metProducto();
    }
    
    Connection connection = null;
    Statement statement = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inicio = new java.awt.Button();
        Cliente = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Clientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ID_Cliente = new javax.swing.JTextField();
        Nombre_Cliente = new javax.swing.JTextField();
        Telefono_Cliente = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        Aniadir_Cliente = new javax.swing.JButton();
        Editar_boton = new javax.swing.JButton();
        Eliminar_Cliente = new javax.swing.JButton();
        Info_Clientes = new javax.swing.JButton();
        ProductoBoton = new java.awt.Button();
        java.awt.Button CategoriaBoton = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        OrdenCompra = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        Boton_Usuario = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        Historial_Boton = new java.awt.Button();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyStock");
        setBackground(new java.awt.Color(102, 153, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(979, 476));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setActionCommand("Inicio");
        Inicio.setBackground(new java.awt.Color(0, 51, 204));
        Inicio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setLabel("Inicio");
        Inicio.setMinimumSize(new java.awt.Dimension(112, 27));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, 40));

        Cliente.setActionCommand("Cliente");
        Cliente.setBackground(new java.awt.Color(0, 51, 204));
        Cliente.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setLabel("Cliente");
        Cliente.setMinimumSize(new java.awt.Dimension(112, 27));
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 120, 40));

        Tabla_Clientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Tabla_Clientes.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        Tabla_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre", "Teléfono", "E-mail"
            }
        ));
        Tabla_Clientes.setGridColor(new java.awt.Color(204, 204, 204));
        Tabla_Clientes.setShowGrid(true);
        Tabla_Clientes.getTableHeader().setReorderingAllowed(false);
        Tabla_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Clientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 441, 240));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, 33));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("ID Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("E-mail:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        ID_Cliente.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 113, -1));

        Nombre_Cliente.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(Nombre_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 113, -1));

        Telefono_Cliente.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(Telefono_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 113, -1));

        correo.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 113, -1));

        Aniadir_Cliente.setBackground(new java.awt.Color(0, 153, 255));
        Aniadir_Cliente.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Aniadir_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Aniadir_Cliente.setText("Añadir Cliente");
        Aniadir_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Aniadir_ClienteMouseClicked(evt);
            }
        });
        jPanel1.add(Aniadir_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 140, -1));

        Editar_boton.setBackground(new java.awt.Color(0, 153, 255));
        Editar_boton.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Editar_boton.setForeground(new java.awt.Color(255, 255, 255));
        Editar_boton.setText("Editar Cliente");
        Editar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar_botonMouseClicked(evt);
            }
        });
        jPanel1.add(Editar_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 140, -1));

        Eliminar_Cliente.setBackground(new java.awt.Color(0, 153, 255));
        Eliminar_Cliente.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Eliminar_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Cliente.setText("Eliminar Cliente");
        Eliminar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_ClienteMouseClicked(evt);
            }
        });
        jPanel1.add(Eliminar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 140, -1));

        Info_Clientes.setBackground(new java.awt.Color(255, 204, 51));
        Info_Clientes.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        Info_Clientes.setText("i");
        Info_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Info_ClientesMouseClicked(evt);
            }
        });
        Info_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_ClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Info_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, -1));

        ProductoBoton.setActionCommand("Producto");
        ProductoBoton.setBackground(new java.awt.Color(0, 51, 204));
        ProductoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductoBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ProductoBoton.setForeground(new java.awt.Color(255, 255, 255));
        ProductoBoton.setLabel("Producto");
        ProductoBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        ProductoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoBotonMouseClicked(evt);
            }
        });
        jPanel1.add(ProductoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 40));

        CategoriaBoton.setActionCommand("Categoría");
        CategoriaBoton.setBackground(new java.awt.Color(0, 51, 204));
        CategoriaBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CategoriaBoton.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaBoton.setLabel("Categoría");
        CategoriaBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        CategoriaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaBotonMouseClicked(evt);
            }
        });
        jPanel1.add(CategoriaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 120, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caja_icono.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_list_icon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 20, 30));

        OrdenCompra.setActionCommand("Orden de compra");
        OrdenCompra.setBackground(new java.awt.Color(0, 51, 204));
        OrdenCompra.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        OrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        OrdenCompra.setLabel("Orden de compra");
        OrdenCompra.setMinimumSize(new java.awt.Dimension(112, 27));
        OrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdenCompraMouseClicked(evt);
            }
        });
        jPanel1.add(OrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 120, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 20, 30));

        Boton_Usuario.setActionCommand("Usuario");
        Boton_Usuario.setBackground(new java.awt.Color(0, 51, 204));
        Boton_Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Boton_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Usuario.setLabel("Usuario");
        Boton_Usuario.setMinimumSize(new java.awt.Dimension(112, 27));
        Boton_Usuario.setName(""); // NOI18N
        Boton_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_UsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 120, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_icon.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        Historial_Boton.setActionCommand("Historial");
        Historial_Boton.setBackground(new java.awt.Color(0, 51, 204));
        Historial_Boton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Historial_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Historial_Boton.setLabel("Historial");
        Historial_Boton.setMinimumSize(new java.awt.Dimension(112, 27));
        Historial_Boton.setName(""); // NOI18N
        Historial_Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Historial_BotonMouseClicked(evt);
            }
        });
        jPanel1.add(Historial_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 120, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/custome_icon.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Captura de pantalla 2022-05-12 141529.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 60, 120));

        jTextField1.setBackground(new java.awt.Color(0, 51, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 270, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean condition_do(){
        
        try {
            int a = Integer.parseInt(ID_Cliente.getText());
            double b = Double.parseDouble(Telefono_Cliente.getText());
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    public void metProducto(){
        
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM cliente");
            Tabla_Clientes.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(SQLException ex){
            
        }
    }
    
    private int get_names(String name){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM cliente");
            ArrayList<String> list_names = new ArrayList<String>();
            while(rs.next()){
                
                String MyCliente = rs.getString("Nombre");
                list_names.add(MyCliente);
            }
            boolean TheReturn = list_names.contains(name);
            if (TheReturn == true) return 1;
            else return 2;
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Error de conexion");
            
        }return 3;
        
    }
    
    
    
    private void Aniadir_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Aniadir_ClienteMouseClicked
        // TODO add your handling code here:
        
        boolean condition_now = condition_do();
        try{
            if(ID_Cliente.getText().isEmpty() || Nombre_Cliente.getText().isEmpty() || Telefono_Cliente.getText().isEmpty() || correo.getText().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "Falta información");
            }else if(condition_now == false){
                
                JOptionPane.showMessageDialog(this, "Datos inválidos");
            
            }else if(Integer.valueOf(ID_Cliente.getText()) > 0){
            
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                PreparedStatement add = connection.prepareStatement("INSERT INTO cliente VALUES(?,?,?,?)");
                add.setInt(1, Integer.valueOf(ID_Cliente.getText()));
                add.setString(2, Nombre_Cliente.getText());
                add.setString(3, Telefono_Cliente.getText());
                add.setString(4, correo.getText());

                int condition;

                condition = get_names(Nombre_Cliente.getText());
                int condition_ID_ = get_ID(Integer.valueOf(ID_Cliente.getText()));

                if ((condition == 2) && (condition_ID_ == 2)){

                    int row = add.executeUpdate();
                    connection.close();
                    metProducto();
                }else if (condition == 1) JOptionPane.showMessageDialog(this,"Este cliente ya existe");
                else if (condition_ID_ == 1) JOptionPane.showMessageDialog(this,"Este ID cliente ya existe");
                else JOptionPane.showMessageDialog(this,"Error de conexion");
            }else JOptionPane.showMessageDialog(this,"Introduzca un ID mayor a 0");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error de conexion");
        }
    }//GEN-LAST:event_Aniadir_ClienteMouseClicked

    private int get_ID(int ID_delete){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM cliente");
            ArrayList list_ID = new ArrayList();
            while(rs.next()){
                
                int MyID_delete = rs.getInt("ID");
                list_ID.add(MyID_delete);
            }
            
            boolean TheReturn_ID = list_ID.contains(ID_delete);
            if (TheReturn_ID == true) return 1;
            else return 2;
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Error de conexion");
            
        }return 3;
        
    }
    
    public boolean condition_delete(){
        
        try {
            int a = Integer.parseInt(ID_Cliente.getText());
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    private void Eliminar_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_ClienteMouseClicked
        // TODO add your handling code here:
        
        boolean delete_this = condition_delete();
        if (ID_Cliente.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Seleccione ID del cliente \nque quiere eliminar");
        }else if(delete_this == false){
            JOptionPane.showMessageDialog(this, "Datos Inválidos");
        }else{
            
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                int MyID = Integer.valueOf(ID_Cliente.getText());
                String SQLLanguage = "DELETE FROM cliente WHERE ID = " + MyID;
                Statement delete = connection.createStatement();
                
                int condition_delete;
                condition_delete = get_ID(MyID);
                
                if (condition_delete == 1){
                    delete.executeUpdate(SQLLanguage);
                    metProducto();
                }else if (condition_delete == 2) JOptionPane.showMessageDialog(this, "Introduzca un ID Cliente existente");
                else JOptionPane.showMessageDialog(this, "Error de conexion");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error de conexion");
            }
        }
    }//GEN-LAST:event_Eliminar_ClienteMouseClicked

    private int MyOld_ID(){
        
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("Select * FROM cliente WHERE Nombre = '" + Nombre_Cliente.getText() + "'");
            String Old_ID = "";
            while(rs.next()){
                
                String MyID_Old = rs.getInt("ID") + "";
                Old_ID += MyID_Old;
            }
            return Integer.valueOf(Old_ID);
        } catch (Exception e) {
        }return -1;
    }
    
    private void Editar_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_botonMouseClicked
        // TODO add your handling code here:
        
        boolean condition_now = condition_do();
        
        if(ID_Cliente.getText().isEmpty() || Nombre_Cliente.getText().isEmpty() || Telefono_Cliente.getText().isEmpty() || correo.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Falta información");
        }else if(condition_now == false){
                
                JOptionPane.showMessageDialog(this, "Datos inválidos");   
        }else{
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                
                int MyID = Integer.valueOf(ID_Cliente.getText());
                
                int condition_editar;
                condition_editar = get_ID(MyID);
                int condition_editar_2 = get_names(Nombre_Cliente.getText());
                int Old_ID = MyOld_ID();
                
                if((condition_editar == 1 && condition_editar_2 == 2) || (condition_editar == 1 && condition_editar_2 == 1 && (MyID == Old_ID))){
                    
                    String SQLLanguage = "DELETE FROM cliente WHERE ID = " + MyID;
                    Statement delete = connection.createStatement();
                    delete.executeUpdate(SQLLanguage);

                    PreparedStatement add = connection.prepareStatement("INSERT INTO cliente VALUES(?,?,?,?)");
                    add.setInt(1, Integer.valueOf(ID_Cliente.getText()));
                    add.setString(2, Nombre_Cliente.getText());
                    add.setString(3, Telefono_Cliente.getText());
                    add.setString(4, correo.getText());

                    int row = add.executeUpdate();
                    connection.close();
                    metProducto();
                
                }else if(condition_editar == 2) JOptionPane.showMessageDialog(this, "Introduzca un ID cliente existente");
                else if(condition_editar_2 == 1) JOptionPane.showMessageDialog(this, "Introduzca un nombre cliente \nno repetido");
                else JOptionPane.showMessageDialog(this, "Error de conexion");

            }catch (SQLException e) {
                
                JOptionPane.showMessageDialog(this, "Error de conexion");
                
            }
        }
    }//GEN-LAST:event_Editar_botonMouseClicked

    private void Tabla_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ClientesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tabla_Clientes.getModel();
        int MyIndex = Tabla_Clientes.getSelectedRow();
        ID_Cliente.setText(model.getValueAt(MyIndex, 0).toString());
        Nombre_Cliente.setText(model.getValueAt(MyIndex, 1).toString());
        Telefono_Cliente.setText(model.getValueAt(MyIndex, 2).toString());
        correo.setText(model.getValueAt(MyIndex, 3).toString());
    }//GEN-LAST:event_Tabla_ClientesMouseClicked

    private void Info_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Info_ClientesMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Pestaña para ver y editar \nlos clientes de la empresa");
    }//GEN-LAST:event_Info_ClientesMouseClicked

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        // TODO add your handling code here:
        Inicio jfInicio =new Inicio();
        jfInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ProductoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoBotonMouseClicked
        // TODO add your handling code here:
        ProductoJframe jfprod =new ProductoJframe();
        jfprod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProductoBotonMouseClicked

    private void CategoriaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaBotonMouseClicked
        // TODO add your handling code here:
        CategoriaJframe jfcat =new CategoriaJframe();
        jfcat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CategoriaBotonMouseClicked

    private void OrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenCompraMouseClicked
        // TODO add your handling code here:
        Orden_de_Compra odp = new Orden_de_Compra();
        odp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OrdenCompraMouseClicked

    private void Boton_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_UsuarioMouseClicked
        // TODO add your handling code here:
        if (My_User_Connected.equals("Administrador")){
            Usuarios My_User = new Usuarios();
            My_User.setVisible(true);
            this.setVisible(false);
        }else JOptionPane.showMessageDialog(this,"Usted no tiene acceso a esta sección");
    }//GEN-LAST:event_Boton_UsuarioMouseClicked

    private void Historial_BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_BotonMouseClicked
        // TODO add your handling code here:
        Historial jfHistorial =new Historial();
        jfHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Historial_BotonMouseClicked

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteActionPerformed

    private void Info_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Info_ClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aniadir_Cliente;
    private java.awt.Button Boton_Usuario;
    private java.awt.Button Cliente;
    private javax.swing.JButton Editar_boton;
    private javax.swing.JButton Eliminar_Cliente;
    private java.awt.Button Historial_Boton;
    private javax.swing.JTextField ID_Cliente;
    private javax.swing.JButton Info_Clientes;
    private java.awt.Button Inicio;
    private javax.swing.JTextField Nombre_Cliente;
    private java.awt.Button OrdenCompra;
    private java.awt.Button ProductoBoton;
    private javax.swing.JTable Tabla_Clientes;
    private javax.swing.JTextField Telefono_Cliente;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
