/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javainventario;

import JavaInventario.Login;
import static JavaInventario.Login.My_User_Connected;
import javax.swing.JOptionPane;

/**
 *
 * @author 57313
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inicio = new java.awt.Button();
        ProductoBoton = new java.awt.Button();
        java.awt.Button CategoriaBoton = new java.awt.Button();
        Cliente = new java.awt.Button();
        OrdenCompra = new java.awt.Button();
        Boton_Usuario = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        Historial_Boton = new java.awt.Button();
        Go_Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyStock");
        setBackground(new java.awt.Color(102, 153, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(979, 476));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setActionCommand("Inicio");
        Inicio.setBackground(new java.awt.Color(0, 51, 204));
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setLabel("Inicio");
        Inicio.setMinimumSize(new java.awt.Dimension(112, 27));
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        ProductoBoton.setActionCommand("Producto");
        ProductoBoton.setBackground(new java.awt.Color(0, 51, 204));
        ProductoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductoBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ProductoBoton.setForeground(new java.awt.Color(255, 255, 255));
        ProductoBoton.setLabel("Producto");
        ProductoBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        ProductoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoBotonMouseClicked(evt);
            }
        });
        jPanel1.add(ProductoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 120, 40));

        CategoriaBoton.setActionCommand("Categoría");
        CategoriaBoton.setBackground(new java.awt.Color(0, 51, 204));
        CategoriaBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CategoriaBoton.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaBoton.setLabel("Categoría");
        CategoriaBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        CategoriaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaBotonMouseClicked(evt);
            }
        });
        jPanel1.add(CategoriaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 120, 40));

        Cliente.setActionCommand("Cliente");
        Cliente.setBackground(new java.awt.Color(0, 51, 204));
        Cliente.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setLabel("Cliente");
        Cliente.setMinimumSize(new java.awt.Dimension(112, 27));
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });
        jPanel1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 40));

        OrdenCompra.setActionCommand("Orden de compra");
        OrdenCompra.setBackground(new java.awt.Color(0, 51, 204));
        OrdenCompra.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        OrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        OrdenCompra.setLabel("Orden de compra");
        OrdenCompra.setMinimumSize(new java.awt.Dimension(112, 27));
        OrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdenCompraMouseClicked(evt);
            }
        });
        jPanel1.add(OrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 120, 40));

        Boton_Usuario.setActionCommand("Usuario");
        Boton_Usuario.setBackground(new java.awt.Color(0, 51, 204));
        Boton_Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Boton_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Usuario.setLabel("Usuario");
        Boton_Usuario.setMinimumSize(new java.awt.Dimension(112, 27));
        Boton_Usuario.setName(""); // NOI18N
        Boton_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_UsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 120, 40));

        label1.setBackground(new java.awt.Color(242, 242, 242));
        label1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label1.setText("de los productos, mediante el registro de los movimientos de la mercancía a través de las ventas. Adicionalmente, brinda");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        label2.setBackground(new java.awt.Color(242, 242, 242));
        label2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 102, 255));
        label2.setText("Integrantes del Proyecto:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));
        label2.getAccessibleContext().setAccessibleName("label1");

        label3.setBackground(new java.awt.Color(242, 242, 242));
        label3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label3.setText("MyStock es un Sistema de Gestión de Inventario que permite efectuar un control sobre los niveles de existencias o inventarios");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        label4.setBackground(new java.awt.Color(242, 242, 242));
        label4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label4.setText("información sobre los clientes y su historial de compras.");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        label5.setBackground(new java.awt.Color(255, 153, 51));
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 51, 204));
        label5.setText(" INVENTARIO MYSTOCK");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        label6.setBackground(new java.awt.Color(242, 242, 242));
        label6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label6.setText("Andres Felipe Mendoza Rosero");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, -1, -1));

        label7.setBackground(new java.awt.Color(242, 242, 242));
        label7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label7.setText("Abraham Felipe Masmela Ramirez");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        label8.setBackground(new java.awt.Color(242, 242, 242));
        label8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label8.setText("Juan David Alonso Leal");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        label9.setBackground(new java.awt.Color(242, 242, 242));
        label9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label9.setText("Juan Carlos Naranjo Jaramillo");
        jPanel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        label10.setBackground(new java.awt.Color(242, 242, 242));
        label10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        label10.setText("Jhonatan Steven Gonzalez Fajardo");
        jPanel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        Historial_Boton.setActionCommand("Historial");
        Historial_Boton.setBackground(new java.awt.Color(0, 51, 204));
        Historial_Boton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Historial_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Historial_Boton.setLabel("Historial");
        Historial_Boton.setMinimumSize(new java.awt.Dimension(112, 27));
        Historial_Boton.setName(""); // NOI18N
        Historial_Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Historial_BotonMouseClicked(evt);
            }
        });
        jPanel1.add(Historial_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 120, 40));

        Go_Login.setBackground(new java.awt.Color(0, 51, 255));
        Go_Login.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Go_Login.setForeground(new java.awt.Color(255, 255, 255));
        Go_Login.setText("Exit to Login");
        Go_Login.setBorder(null);
        Go_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Go_LoginMouseClicked(evt);
            }
        });
        jPanel1.add(Go_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Captura de pantalla 2022-05-12 141529.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caja_icono.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category_icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/custome_icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_list_icon.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 20, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 20, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_icon.png"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 870, 520));

        jTextField2.setBackground(new java.awt.Color(255, 153, 102));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 870, 80));

        jTextField1.setBackground(new java.awt.Color(0, 51, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Go_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Go_LoginMouseClicked
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Desea cerrar sesion??");
        if(answer == JOptionPane.YES_OPTION){
            Login Login_again =new Login();
            Login_again.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Go_LoginMouseClicked

    private void Historial_BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_BotonMouseClicked
        // TODO add your handling code here:
        Historial jfHistorial =new Historial();
        jfHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Historial_BotonMouseClicked

    private void Boton_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_UsuarioMouseClicked
        // TODO add your handling code here:
        if (My_User_Connected.equals("Administrador")){
            Usuarios My_User = new Usuarios();
            My_User.setVisible(true);
            this.setVisible(false);
        }else JOptionPane.showMessageDialog(this,"Usted no tiene acceso a esta sección");
    }//GEN-LAST:event_Boton_UsuarioMouseClicked

    private void OrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenCompraMouseClicked
        // TODO add your handling code here:
        Orden_de_Compra odp = new Orden_de_Compra();
        odp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OrdenCompraMouseClicked

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        // TODO add your handling code here:
        Clientes jfCliente =new Clientes();
        jfCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ClienteMouseClicked

    private void CategoriaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaBotonMouseClicked
        // TODO add your handling code here:
        CategoriaJframe jfcat =new CategoriaJframe();
        jfcat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CategoriaBotonMouseClicked

    private void ProductoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoBotonMouseClicked
        // TODO add your handling code here:
        ProductoJframe jfprod =new ProductoJframe();
        jfprod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProductoBotonMouseClicked

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Boton_Usuario;
    private java.awt.Button Cliente;
    private javax.swing.JButton Go_Login;
    private java.awt.Button Historial_Boton;
    private java.awt.Button Inicio;
    private java.awt.Button OrdenCompra;
    private java.awt.Button ProductoBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
