/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javainventario;

import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import static JavaInventario.Login.My_User_Connected;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author fabid
 */
public class ProductoJframe extends javax.swing.JFrame {
    /**
     * Creates new form ProductoJframe
     */
    
    public ProductoJframe() {
        initComponents();
        metProducto();
        get_category();
        
    }
    
    Connection connection = null;
    Statement statement = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Categoria_Producto = new javax.swing.JComboBox<>();
        Cantidad_Producto = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        NombreProducto = new javax.swing.JTextField();
        IDproducto = new javax.swing.JTextField();
        tabla_panel = new javax.swing.JScrollPane();
        Productos_tabla = new javax.swing.JTable();
        btnaniadir = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnproducpro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Inicio = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        java.awt.Button CategoriaBoton = new java.awt.Button();
        jLabel12 = new javax.swing.JLabel();
        Cliente = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        OrdenCompra = new java.awt.Button();
        jLabel13 = new javax.swing.JLabel();
        Boton_Usuario = new java.awt.Button();
        jLabel14 = new javax.swing.JLabel();
        Historial_Boton = new java.awt.Button();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyStock");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("Producto"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("ID Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 84, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 84, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Descripción");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 84, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setText("Precio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 84, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 84, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setText("Categoria");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 84, -1));

        Categoria_Producto.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(Categoria_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 148, -1));

        Cantidad_Producto.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(Cantidad_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 148, -1));

        Precio.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 148, -1));

        Descripcion.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 148, -1));

        NombreProducto.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 148, -1));

        IDproducto.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel1.add(IDproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 148, -1));

        tabla_panel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Productos_tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Productos_tabla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Productos_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Productos_tabla.getTableHeader().setReorderingAllowed(false);
        Productos_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Productos_tablaMouseClicked(evt);
            }
        });
        tabla_panel.setViewportView(Productos_tabla);

        jPanel1.add(tabla_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 389, 307));

        btnaniadir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnaniadir.setText("Añadir");
        btnaniadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaniadirMouseClicked(evt);
            }
        });
        jPanel1.add(btnaniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        btneditar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btneditar.setText("Editar");
        btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditarMouseClicked(evt);
            }
        });
        jPanel1.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        btneliminar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Producto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        btnproducpro.setBackground(new java.awt.Color(0, 51, 204));
        btnproducpro.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnproducpro.setForeground(new java.awt.Color(255, 255, 255));
        btnproducpro.setText("Producto");
        btnproducpro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnproducpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproducproActionPerformed(evt);
            }
        });
        jPanel1.add(btnproducpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Captura de pantalla 2022-05-12 141529.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 120));

        Inicio.setActionCommand("Inicio");
        Inicio.setBackground(new java.awt.Color(0, 51, 204));
        Inicio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setLabel("Inicio");
        Inicio.setMinimumSize(new java.awt.Dimension(112, 27));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 120, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category_icon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        CategoriaBoton.setActionCommand("Categoría");
        CategoriaBoton.setBackground(new java.awt.Color(0, 51, 204));
        CategoriaBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CategoriaBoton.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaBoton.setLabel("Categoría");
        CategoriaBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        CategoriaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaBotonMouseClicked(evt);
            }
        });
        jPanel1.add(CategoriaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/custome_icon.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        Cliente.setActionCommand("Cliente");
        Cliente.setBackground(new java.awt.Color(0, 51, 204));
        Cliente.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setLabel("Cliente");
        Cliente.setMinimumSize(new java.awt.Dimension(112, 27));
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 120, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_list_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 20, 30));

        OrdenCompra.setActionCommand("Orden de compra");
        OrdenCompra.setBackground(new java.awt.Color(0, 51, 204));
        OrdenCompra.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        OrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        OrdenCompra.setLabel("Orden de compra");
        OrdenCompra.setMinimumSize(new java.awt.Dimension(112, 27));
        OrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdenCompraMouseClicked(evt);
            }
        });
        jPanel1.add(OrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 120, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_icon.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 20, 30));

        Boton_Usuario.setActionCommand("Usuario");
        Boton_Usuario.setBackground(new java.awt.Color(0, 51, 204));
        Boton_Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Boton_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Usuario.setLabel("Usuario");
        Boton_Usuario.setMinimumSize(new java.awt.Dimension(112, 27));
        Boton_Usuario.setName(""); // NOI18N
        Boton_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_UsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 120, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_icon.png"))); // NOI18N
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        Historial_Boton.setActionCommand("Historial");
        Historial_Boton.setBackground(new java.awt.Color(0, 51, 204));
        Historial_Boton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Historial_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Historial_Boton.setLabel("Historial");
        Historial_Boton.setMinimumSize(new java.awt.Dimension(112, 27));
        Historial_Boton.setName(""); // NOI18N
        Historial_Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Historial_BotonMouseClicked(evt);
            }
        });
        jPanel1.add(Historial_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 120, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caja_icono.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 51, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnproducproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproducproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproducproActionPerformed

    
    public void metProducto(){
        
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM producto");
            Productos_tabla.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(SQLException ex){
            
        }
    }
    
    private void get_category(){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM categoria");
            while(rs.next()){
                
                String MyCategory = rs.getString("Nombre");
                Categoria_Producto.addItem(MyCategory);
            }
            
        }catch(SQLException e){
            
        }
    }
    
    private int get_names(String name){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM producto");
            ArrayList<String> list_names = new ArrayList<String>();
            while(rs.next()){
                
                String MyCategory = rs.getString("Nombre");
                list_names.add(MyCategory);  //Estructura de datos
            }
            
            boolean TheReturn = list_names.contains(name);
            if (TheReturn == true) return 1;
            else return 2;
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Error de conexion");
            
        }return 3;
        
    }
     
  public boolean condiciones(){
      
      try{
          
          int a = Integer.valueOf(IDproducto.getText());
          int b = Integer.valueOf(Cantidad_Producto.getText());
          double c = Double. parseDouble(Precio.getText());
          
          return true;
          
      } catch (NumberFormatException ex){
          
          return false;
      }
      
  }
    
    
    private void btnaniadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaniadirMouseClicked
        // TODO add your handling code here:
        
        boolean condiciones_codigo = condiciones();
        try{
            if(IDproducto.getText().isEmpty() || NombreProducto.getText().isEmpty() || Descripcion.getText().isEmpty() || Precio.getText().isEmpty() || Cantidad_Producto.getText().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "Falta información");
            
            }else if (condiciones_codigo == false){   
                
                JOptionPane.showMessageDialog(this,"Tipo de datos Inválidos");

            }else if(Integer.valueOf(IDproducto.getText()) > 0 && Integer.valueOf(Cantidad_Producto.getText()) >= 0){
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                PreparedStatement add = connection.prepareStatement("INSERT INTO producto VALUES(?,?,?,?,?,?)");
                add.setInt(1, Integer.valueOf(IDproducto.getText()));
                add.setString(2, NombreProducto.getText());
                add.setString(3, Descripcion.getText());
                add.setInt(4, Integer.valueOf(Precio.getText()));
                add.setString(5, Categoria_Producto.getSelectedItem().toString());
                add.setInt(6, Integer.valueOf(Cantidad_Producto.getText()));

                int condition;

                condition = get_names(NombreProducto.getText());
                int condition_ID_ = get_ID(Integer.valueOf(IDproducto.getText()));

                if ((condition == 2) && (condition_ID_ == 2)){

                    int row = add.executeUpdate();
                    connection.close();
                    metProducto();
                }else if (condition == 1) JOptionPane.showMessageDialog(this,"El producto ya existe");
                else if (condition_ID_ == 1) JOptionPane.showMessageDialog(this,"Este ID cliente ya existe");
                else JOptionPane.showMessageDialog(this,"Error de conexion");
            }else if (Integer.valueOf(Cantidad_Producto.getText()) <= 0) JOptionPane.showMessageDialog(this,"Introduzca una cantidad \nmayor a 0");
            else JOptionPane.showMessageDialog(this,"Introduzca un \nID >= 0");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error de conexion");
        }
        
    }//GEN-LAST:event_btnaniadirMouseClicked

    private int get_ID(int ID_delete){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM producto");
            ArrayList list_ID = new ArrayList();
            while(rs.next()){
                
                int MyID_delete = rs.getInt("ID");
                list_ID.add(MyID_delete);
            }
            
            boolean TheReturn_ID = list_ID.contains(ID_delete);
            if (TheReturn_ID == true) return 1;
            else return 2;
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Error de conexion");
            
        }return 3;
        
    }
    
    public boolean condition_to_delete(){
        
        try {
            int a = Integer.parseInt(IDproducto.getText());
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
        // TODO add your handling code here:
        
        boolean condition_this = condition_to_delete();
        if (IDproducto.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Seleccione ID del producto \nque quiere eliminar");
        }else if (condition_this == false){
            JOptionPane.showMessageDialog(this, "Tipo de dato Inválido");
        }else{
            
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                int MyID = Integer.valueOf(IDproducto.getText());
                String SQLLanguage = "DELETE FROM PRODUCTO WHERE ID = " + MyID;
                Statement delete = connection.createStatement();
                
                int condition_delete;
                condition_delete = get_ID(MyID);
                
                if (condition_delete == 1){
                    delete.executeUpdate(SQLLanguage);
                    metProducto();
                }else if (condition_delete == 2) JOptionPane.showMessageDialog(this, "Introduzca un ID \nexistente");
                else JOptionPane.showMessageDialog(this, "Error de conexion");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error de conexion");
            }
        }
    }//GEN-LAST:event_btneliminarMouseClicked

    private int MyOld_ID(){
        
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("Select * FROM PRODUCTO WHERE Nombre = '" + NombreProducto.getText() + "'");
            String Old_ID = "";
            while(rs.next()){
                
                String MyID_Old = rs.getInt("ID") + "";
                Old_ID += MyID_Old;
            }
            return Integer.valueOf(Old_ID);
        } catch (Exception e) {
        }return -1;
    }
    
    private void btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditarMouseClicked
        // TODO add your handling code here:
        
        boolean condiciones_codigo = condiciones();
        
        if(IDproducto.getText().isEmpty() || NombreProducto.getText().isEmpty() || Descripcion.getText().isEmpty() || Precio.getText().isEmpty() || Cantidad_Producto.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Falta información");
        }else if (condiciones_codigo == false){
            JOptionPane.showMessageDialog(this, "Tipo de dato Inválido");   
        }else{
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                
                int MyID = Integer.valueOf(IDproducto.getText());
                
                int condition_editar;
                condition_editar = get_ID(MyID);
                int condition_editar_2 = get_names(NombreProducto.getText());
                int Old_ID = MyOld_ID();
                
                if((condition_editar == 1 && condition_editar_2 == 2) || (condition_editar == 1 && condition_editar_2 == 1 && (MyID == Old_ID))){
                    
                    String SQLLanguage = "DELETE FROM PRODUCTO WHERE ID = " + MyID;
                    Statement delete = connection.createStatement();
                    delete.executeUpdate(SQLLanguage);

                    PreparedStatement add = connection.prepareStatement("INSERT INTO producto VALUES(?,?,?,?,?,?)");
                    add.setInt(1, Integer.valueOf(IDproducto.getText()));
                    add.setString(2, NombreProducto.getText());
                    add.setString(3, Descripcion.getText());
                    add.setInt(4, Integer.valueOf(Precio.getText()));
                    add.setString(5, Categoria_Producto.getSelectedItem().toString());
                    add.setInt(6, Integer.valueOf(Cantidad_Producto.getText()));

                    int row = add.executeUpdate();
                    connection.close();
                    metProducto();
                    
                }else if(condition_editar == 2) JOptionPane.showMessageDialog(this, "Introduzca un ID \nProducto existente");
                else if(condition_editar_2 == 1) JOptionPane.showMessageDialog(this, "Introduzca un nombre \nProducto no repetido");
                else JOptionPane.showMessageDialog(this, "Error de conexion");

            }catch (SQLException e) {
                
                JOptionPane.showMessageDialog(this, "No se puede editar \nel producto");
                
            }
        }
    }//GEN-LAST:event_btneditarMouseClicked

    private void Productos_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Productos_tablaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Productos_tabla.getModel();
        int MyIndex = Productos_tabla.getSelectedRow();
        IDproducto.setText(model.getValueAt(MyIndex, 0).toString());
        NombreProducto.setText(model.getValueAt(MyIndex, 1).toString());
        Descripcion.setText(model.getValueAt(MyIndex, 2).toString());
        Precio.setText(model.getValueAt(MyIndex, 3).toString());
        //Categoria_Producto.setText(model.getValueAt(MyIndex, 4).toString());
        Cantidad_Producto.setText(model.getValueAt(MyIndex, 5).toString());
    }//GEN-LAST:event_Productos_tablaMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        // TODO add your handling code here:
        Inicio jfInicio =new Inicio();
        jfInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioMouseClicked

    private void CategoriaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaBotonMouseClicked
        // TODO add your handling code here:
        CategoriaJframe jfcat =new CategoriaJframe();
        jfcat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CategoriaBotonMouseClicked

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
        Clientes jfCliente =new Clientes();
        jfCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ClienteActionPerformed

    private void OrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenCompraMouseClicked
        // TODO add your handling code here:
        Orden_de_Compra odp = new Orden_de_Compra();
        odp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OrdenCompraMouseClicked

    private void Boton_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_UsuarioMouseClicked
        // TODO add your handling code here:
        if (My_User_Connected.equals("Administrador")){
            Usuarios My_User = new Usuarios();
            My_User.setVisible(true);
            this.setVisible(false);
        }else JOptionPane.showMessageDialog(this,"Usted no tiene acceso a esta sección");
    }//GEN-LAST:event_Boton_UsuarioMouseClicked

    private void Historial_BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_BotonMouseClicked
        // TODO add your handling code here:
        Historial jfHistorial =new Historial();
        jfHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Historial_BotonMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProductoJframe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Boton_Usuario;
    private javax.swing.JTextField Cantidad_Producto;
    private javax.swing.JComboBox<String> Categoria_Producto;
    private java.awt.Button Cliente;
    private javax.swing.JTextField Descripcion;
    private java.awt.Button Historial_Boton;
    private javax.swing.JTextField IDproducto;
    private java.awt.Button Inicio;
    private javax.swing.JTextField NombreProducto;
    private java.awt.Button OrdenCompra;
    private javax.swing.JTextField Precio;
    private javax.swing.JTable Productos_tabla;
    private javax.swing.JButton btnaniadir;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnproducpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane tabla_panel;
    // End of variables declaration//GEN-END:variables
}
