/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javainventario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuarios() {
        initComponents();
        metUsuario();
    }
    
    Connection connection = null;
    Statement statement = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuario_Boton = new java.awt.Button();
        label5 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        ID_Usuario = new javax.swing.JTextField();
        Nombre_Vendedor = new javax.swing.JTextField();
        Contrasenia_Usuario = new javax.swing.JTextField();
        Telefono_Usuario = new javax.swing.JTextField();
        Correo_Usuario = new javax.swing.JTextField();
        Aniadir_Usuario = new javax.swing.JButton();
        Editar_Usuario = new javax.swing.JButton();
        Eliminar_Usuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Usuario = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Inicio = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        ProductoBoton = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        java.awt.Button CategoriaBoton = new java.awt.Button();
        jLabel12 = new javax.swing.JLabel();
        Cliente = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        OrdenCompra = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        Historial_Boton = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyStock");
        setBackground(new java.awt.Color(102, 153, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(979, 476));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario_Boton.setActionCommand("Usuario");
        Usuario_Boton.setBackground(new java.awt.Color(0, 51, 204));
        Usuario_Boton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Usuario_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_Boton.setLabel("Usuario");
        Usuario_Boton.setMinimumSize(new java.awt.Dimension(112, 27));
        Usuario_Boton.setName(""); // NOI18N
        Usuario_Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Usuario_BotonMouseClicked(evt);
            }
        });
        jPanel1.add(Usuario_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 120, 40));

        label5.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 102, 255));
        label5.setText("Usuario");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        label9.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        label9.setText("Nombre");
        jPanel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        label10.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        label10.setText("ID Usuario");
        jPanel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        label11.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        label11.setText("Contraseña");
        jPanel1.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        label12.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        label12.setText("Telefono");
        jPanel1.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        label13.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        label13.setText("E-mail");
        jPanel1.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        ID_Usuario.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jPanel1.add(ID_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 135, 27));

        Nombre_Vendedor.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jPanel1.add(Nombre_Vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 135, 27));

        Contrasenia_Usuario.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jPanel1.add(Contrasenia_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 135, 27));

        Telefono_Usuario.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jPanel1.add(Telefono_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 135, 27));

        Correo_Usuario.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jPanel1.add(Correo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 135, 27));

        Aniadir_Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Aniadir_Usuario.setText("Añadir");
        Aniadir_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Aniadir_UsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(Aniadir_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 100, -1));

        Editar_Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Editar_Usuario.setText("Editar");
        Editar_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar_UsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(Editar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 100, -1));

        Eliminar_Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Eliminar_Usuario.setText("Eliminar");
        Eliminar_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_UsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(Eliminar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 100, -1));

        Tabla_Usuario = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Tabla_Usuario.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Tabla_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Contraseña", "Telefono", "E-mail"
            }
        ));
        Tabla_Usuario.getTableHeader().setReorderingAllowed(false);
        Tabla_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_UsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Usuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 429, 268));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Captura de pantalla 2022-05-12 141529.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 60, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Inicio.setActionCommand("Inicio");
        Inicio.setBackground(new java.awt.Color(0, 51, 204));
        Inicio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setLabel("Inicio");
        Inicio.setMinimumSize(new java.awt.Dimension(112, 27));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caja_icono.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        ProductoBoton.setActionCommand("Producto");
        ProductoBoton.setBackground(new java.awt.Color(0, 51, 204));
        ProductoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductoBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ProductoBoton.setForeground(new java.awt.Color(255, 255, 255));
        ProductoBoton.setLabel("Producto");
        ProductoBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        ProductoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoBotonMouseClicked(evt);
            }
        });
        jPanel1.add(ProductoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        CategoriaBoton.setActionCommand("Categoría");
        CategoriaBoton.setBackground(new java.awt.Color(0, 51, 204));
        CategoriaBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CategoriaBoton.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaBoton.setLabel("Categoría");
        CategoriaBoton.setMinimumSize(new java.awt.Dimension(112, 27));
        CategoriaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaBotonMouseClicked(evt);
            }
        });
        jPanel1.add(CategoriaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 120, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/custome_icon.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        Cliente.setActionCommand("Cliente");
        Cliente.setBackground(new java.awt.Color(0, 51, 204));
        Cliente.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setLabel("Cliente");
        Cliente.setMinimumSize(new java.awt.Dimension(112, 27));
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 120, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_list_icon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 20, 30));

        OrdenCompra.setActionCommand("Orden de compra");
        OrdenCompra.setBackground(new java.awt.Color(0, 51, 204));
        OrdenCompra.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        OrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        OrdenCompra.setLabel("Orden de compra");
        OrdenCompra.setMinimumSize(new java.awt.Dimension(112, 27));
        OrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdenCompraMouseClicked(evt);
            }
        });
        jPanel1.add(OrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 120, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 20, 30));

        Historial_Boton.setActionCommand("Historial");
        Historial_Boton.setBackground(new java.awt.Color(0, 51, 204));
        Historial_Boton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Historial_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Historial_Boton.setLabel("Historial");
        Historial_Boton.setMinimumSize(new java.awt.Dimension(112, 27));
        Historial_Boton.setName(""); // NOI18N
        Historial_Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Historial_BotonMouseClicked(evt);
            }
        });
        jPanel1.add(Historial_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 120, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_icon.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 51, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 270, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void metUsuario(){
        
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM usuario");
            Tabla_Usuario.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(SQLException ex){
            
        }
    }
    
    public boolean condition_do(){
        
        try {
            int a = Integer.parseInt(ID_Usuario.getText());
            double b = Double.parseDouble(Telefono_Usuario.getText());
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    
    private void Usuario_BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Usuario_BotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_BotonMouseClicked

    private void Tabla_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_UsuarioMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tabla_Usuario.getModel();
        int MyIndex = Tabla_Usuario.getSelectedRow();
        ID_Usuario.setText(model.getValueAt(MyIndex, 0).toString());
        Nombre_Vendedor.setText(model.getValueAt(MyIndex, 1).toString());
        Contrasenia_Usuario.setText(model.getValueAt(MyIndex, 2).toString());
        Telefono_Usuario.setText(model.getValueAt(MyIndex, 3).toString());
        Correo_Usuario.setText(model.getValueAt(MyIndex, 4).toString());
    }//GEN-LAST:event_Tabla_UsuarioMouseClicked

    private int get_names(String name){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM usuario");
            ArrayList<String> list_names = new ArrayList<String>();
            while(rs.next()){
                
                String MyUser = rs.getString("Nombre");
                list_names.add(MyUser);
            }
            boolean TheReturn = list_names.contains(name);
            if (TheReturn == true) return 1;
            else return 2;
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Error de conexion");
            
        }return 3;
        
    }
    
    private int get_ID(int ID_delete){
        
        try{
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM usuario");
            ArrayList list_ID = new ArrayList();
            while(rs.next()){
                
                int MyID_delete = rs.getInt("ID");
                list_ID.add(MyID_delete);
            }
            
            boolean TheReturn_ID = list_ID.contains(ID_delete);
            if (TheReturn_ID == true) return 1;
            else return 2;
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Error de conexion");
            
        }return 3;
        
    }
    
    private void Aniadir_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Aniadir_UsuarioMouseClicked
        // TODO add your handling code here:
        try{
            
            boolean my_condition = condition_do();
            if(ID_Usuario.getText().isEmpty() || Nombre_Vendedor.getText().isEmpty() || Contrasenia_Usuario.getText().isEmpty() || Telefono_Usuario.getText().isEmpty() || Correo_Usuario.getText().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "Falta información");
            
            }else if(my_condition == false){
                JOptionPane.showMessageDialog(this, "Tipo de dato inválido");
            }else if(Integer.valueOf(ID_Usuario.getText()) > 0){
            
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                PreparedStatement add = connection.prepareStatement("INSERT INTO usuario VALUES(?,?,?,?,?)");
                add.setInt(1, Integer.valueOf(ID_Usuario.getText()));
                add.setString(2, Nombre_Vendedor.getText());
                add.setString(3, Contrasenia_Usuario.getText());
                add.setString(4, Telefono_Usuario.getText());
                add.setString(5, Correo_Usuario.getText());

                int condition;

                condition = get_names(Nombre_Vendedor.getText());
                int condition_ID_ = get_ID(Integer.valueOf(ID_Usuario.getText()));

                if ((condition == 2) && (condition_ID_ == 2)){

                    int row = add.executeUpdate();
                    connection.close();
                    metUsuario();
                }else if (condition == 1) JOptionPane.showMessageDialog(this,"Este usuario ya existe");
                else if (condition_ID_ == 1) JOptionPane.showMessageDialog(this,"Este ID usuario ya existe");
                else JOptionPane.showMessageDialog(this,"Error de conexion");
            }else JOptionPane.showMessageDialog(this,"Introduzca un ID mayor a 0");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error de conexion");
        }
    }//GEN-LAST:event_Aniadir_UsuarioMouseClicked
    
    private boolean Administrator_condition(){
        
        try {
            int Id_for_delete = Integer.valueOf(ID_Usuario.getText());
            if (Id_for_delete == 1){
                JOptionPane.showMessageDialog(this, "No se puede eliminar el administrador");
                return false;
            }else return true;
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero entero");
            return false;
        }
    }
    
    private void Eliminar_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_UsuarioMouseClicked
        // TODO add your handling code here:
        boolean posibility_delete = Administrator_condition();
        if (ID_Usuario.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Seleccione ID del usuario \nque quiere eliminar");
        }else if(posibility_delete == true){
            
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                int MyID = Integer.valueOf(ID_Usuario.getText());
                String SQLLanguage = "DELETE FROM usuario WHERE ID = " + MyID;
                Statement delete = connection.createStatement();
                
                int condition_delete;
                condition_delete = get_ID(MyID);
                
                if (condition_delete == 1){
                    delete.executeUpdate(SQLLanguage);
                    metUsuario();
                }else if (condition_delete == 2) JOptionPane.showMessageDialog(this, "Introduzca un ID usuario existente");
                else JOptionPane.showMessageDialog(this, "Error de conexion");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error de conexion");
            }
        }
    }//GEN-LAST:event_Eliminar_UsuarioMouseClicked

    private int MyOld_ID(){
        
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
            statement = connection.createStatement();
            rs = statement.executeQuery("Select * FROM usuario WHERE Nombre = '" + Nombre_Vendedor.getText() + "'");
            String Old_ID = "";
            while(rs.next()){
                
                String MyID_Old = rs.getInt("ID") + "";
                Old_ID += MyID_Old;
            }
            return Integer.valueOf(Old_ID);
        } catch (Exception e) {
        }return -1;
    }
    
    private boolean Administrator_name(){
        
        try {
            int for_condition = Integer.valueOf(ID_Usuario.getText());
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero entero");
            return false;
        }
        
        if (Nombre_Vendedor.getText().equals("Administrador") && (ID_Usuario.getText().equals("1"))){
            return true;
        }
        else if ((Nombre_Vendedor.getText().equals("Administrador") == false) && (ID_Usuario.getText().equals("1"))){
            JOptionPane.showMessageDialog(this, "No se puede modificar el nombre del \nAdministrador");
            return false;
        }else return true;
    }
    
    public boolean telefono_int(){
        
        try {
            double a = Double.parseDouble(Telefono_Usuario.getText());
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    private void Editar_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_UsuarioMouseClicked
        // TODO add your handling code here:
        boolean My_Admin_name = Administrator_name();
        boolean My_good_phone = telefono_int();
        if(ID_Usuario.getText().isEmpty() || Nombre_Vendedor.getText().isEmpty() || Contrasenia_Usuario.getText().isEmpty() || Telefono_Usuario.getText().isEmpty() || Correo_Usuario.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Falta información");
        
        }else if(My_good_phone == false){
            JOptionPane.showMessageDialog(this, "Datos inválidos");
        }else if(My_Admin_name){
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemainventario", "root", "");
                
                int MyID = Integer.valueOf(ID_Usuario.getText());
                
                int condition_editar;
                condition_editar = get_ID(MyID);
                int condition_editar_2 = get_names(Nombre_Vendedor.getText());
                int Old_ID = MyOld_ID();
                
                if((condition_editar == 1 && condition_editar_2 == 2) || (condition_editar == 1 && condition_editar_2 == 1 && (MyID == Old_ID))){
                    
                    String SQLLanguage = "DELETE FROM usuario WHERE ID = " + MyID;
                    Statement delete = connection.createStatement();
                    delete.executeUpdate(SQLLanguage);

                    PreparedStatement add = connection.prepareStatement("INSERT INTO usuario VALUES(?,?,?,?,?)");
                    add.setInt(1, Integer.valueOf(ID_Usuario.getText()));
                    add.setString(2, Nombre_Vendedor.getText());
                    add.setString(3, Contrasenia_Usuario.getText());
                    add.setString(4, Telefono_Usuario.getText());
                    add.setString(5, Correo_Usuario.getText());

                    int row = add.executeUpdate();
                    connection.close();
                    metUsuario();
                
                }else if(condition_editar == 2) JOptionPane.showMessageDialog(this, "Introduzca un ID usuario existente");
                else if(condition_editar_2 == 1) JOptionPane.showMessageDialog(this, "Introduzca un nombre usuario \nno repetido");
                else JOptionPane.showMessageDialog(this, "Error de conexion");

            }catch (SQLException e) {
                
                JOptionPane.showMessageDialog(this, "Error de conexion");
                
            }
        }
    }//GEN-LAST:event_Editar_UsuarioMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        // TODO add your handling code here:
        Inicio jfInicio =new Inicio();
        jfInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioMouseClicked

    private void ProductoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoBotonMouseClicked
        // TODO add your handling code here:
        ProductoJframe jfprod =new ProductoJframe();
        jfprod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProductoBotonMouseClicked

    private void CategoriaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaBotonMouseClicked
        // TODO add your handling code here:
        CategoriaJframe jfcat =new CategoriaJframe();
        jfcat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CategoriaBotonMouseClicked

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
        Clientes jfCliente =new Clientes();
        jfCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ClienteActionPerformed

    private void OrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenCompraMouseClicked
        // TODO add your handling code here:
        Orden_de_Compra odp = new Orden_de_Compra();
        odp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OrdenCompraMouseClicked

    private void Historial_BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_BotonMouseClicked
        // TODO add your handling code here:
        Historial jfHistorial =new Historial();
        jfHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Historial_BotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aniadir_Usuario;
    private java.awt.Button Cliente;
    private javax.swing.JTextField Contrasenia_Usuario;
    private javax.swing.JTextField Correo_Usuario;
    private javax.swing.JButton Editar_Usuario;
    private javax.swing.JButton Eliminar_Usuario;
    private java.awt.Button Historial_Boton;
    private javax.swing.JTextField ID_Usuario;
    private java.awt.Button Inicio;
    private javax.swing.JTextField Nombre_Vendedor;
    private java.awt.Button OrdenCompra;
    private java.awt.Button ProductoBoton;
    private javax.swing.JTable Tabla_Usuario;
    private javax.swing.JTextField Telefono_Usuario;
    private java.awt.Button Usuario_Boton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label5;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
